# https://doc.rust-lang.org/stable/clippy/index.html

doc-valid-idents = [
  "JetStream",
  "MongoDB",
  "NATS",
  "OpenTelemetry",
  "WebAssembly",
  "WebSockets",
]

allowed-duplicate-crates = [
  "const-oid",
  "core-foundation",
  "cpufeatures",
  "darling",
  "darling_core",
  "darling_macro",
  "dashmap",
  "embedded-io",
  "fallible-iterator",
  "fancy-regex",
  "fluent-uri",
  "foldhash",
  "getrandom",
  "hashbrown",
  "jni-sys",
  "jsonschema",
  "linux-raw-sys",
  "openssl-probe",
  "prost",
  "prost-derive",
  "r-efi",
  "rand",
  "rand_chacha",
  "rand_core",
  "referencing",
  "reqwest",
  "rustix",
  "rustls-native-certs",
  "rustls-webpki",
  "security-framework",
  "socket2",
  "thiserror",
  "thiserror-impl",
  "wasi",
  "wasm-encoder",
  "wasm-metadata",
  "wasmparser",
  "webpki-roots",
  "windows-sys",
  "windows-targets",
  "windows_aarch64_gnullvm",
  "windows_aarch64_msvc",
  "windows_i686_gnu",
  "windows_i686_gnullvm",
  "windows_i686_msvc",
  "windows_x86_64_gnu",
  "windows_x86_64_gnullvm",
  "windows_x86_64_msvc",
  "wit-bindgen",
  "wit-bindgen-core",
  "wit-bindgen-rust",
  "wit-bindgen-rust-macro",
  "wit-component",
  "wit-parser",
]
